# Generated by Django 3.0.7 on 2020-06-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetryApp', '0002_feedbackmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='feedbackmodel',
            table=None,
        ),
    ]
