# Generated by Django 3.0.7 on 2020-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetryApp', '0003_auto_20200624_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_img', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('rating', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=80)),
                ('downloads', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'New_App_Data',
            },
        ),
        migrations.CreateModel(
            name='NewSoftwareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_img', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('rating', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=80)),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'New_Soft_Data',
            },
        ),
        migrations.CreateModel(
            name='NewWebSiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_img', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('rank_c', models.CharField(max_length=80)),
                ('rank_g', models.CharField(max_length=80)),
                ('rating', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'New_Web_Data',
            },
        ),
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('search_item', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Search_Item',
            },
        ),
        migrations.AlterModelTable(
            name='contactmodel',
            table='Contact_Info',
        ),
        migrations.AlterModelTable(
            name='feedbackmodel',
            table='Feedback',
        ),
    ]
