# Generated by Django 3.0.7 on 2020-06-17 11:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreateModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Credential',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='b4.jpg', upload_to='profile_pics')),
                ('Age', models.CharField(choices=[('below 15', 'Below 15'), ('15-20', '15-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('Above 40', 'Above 40')], default='Age', max_length=50)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='gender', max_length=20)),
                ('Education', models.CharField(choices=[('Natural and Physical Sciences', 'Natural and Physical Sciences'), ('Information Technology', 'Information Technology'), ('Engineering and Related Technologies', 'Engineering and Related Technologies'), ('Architecture and Building', 'Architecture and Building'), ('Agriculture, Environmental and Related Studies', 'Agriculture, Environmental and Related Studies'), ('Health', 'Health'), ('Education', 'Education'), ('Management and Commerce', 'Management and Commerce'), ('Society and Culture', 'Society and Culture'), ('Creative Arts', 'Creative Arts'), ('Food, Hospitality and Personal Services', 'Food, Hospitality and Personal Services'), ('Mixed Field Programs', 'Mixed Field Programs')], default='Education', max_length=100)),
                ('Profession', models.CharField(choices=[('Professions', 'Professions'), ('Teacher', 'Teacher'), ('Physician', 'Physician'), ('Technician', 'Technician'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Accountant', 'Accountant'), ('Architect', 'Architect'), ('Electrician', 'Electrician'), ('Veterinarian', 'Veterinarian'), ('Software Developer', 'Software Developer'), ('Pharmacist', 'Pharmacist'), ('Surveyor', 'Surveyor'), ('Dietitian', 'Dietitian'), ('Plumber', 'Plumber'), ('Consultant', 'Consultant'), ('Hairdresser', 'Hairdresser'), ('Chef', 'Chef'), ('Technologist', 'Technologist'), ('Mechanic', 'Mechanic'), ('Police officer', 'Police officer'), ('Dental hygienist', 'Dental hygienist'), ('Radiographer', 'Radiographer'), ('Actuary', 'Actuary'), ('Artist', 'Artist'), ('Waiting staff', 'Waiting staff'), ('Biomedical Engineer', 'Biomedical Engineer'), ('Firefighter', 'Firefighter'), ('Actor', 'Actor'), ('Surgeon', 'Surgeon'), ('Designer', 'Designer'), ('Broker', 'Broker'), ('Labourer', 'Labourer'), ('Scientist', 'Scientist'), ('Secretary', 'Secretary'), ('Librarian', 'Librarian'), ('Aviator', 'Aviator'), ('Estate agent', 'Estate agent'), ('Barber', 'Barber'), ('Physiotherapist', 'Physiotherapist'), ('Dentist', 'Dentist'), ('Athlete', 'Athlete'), ('Judge', 'Judge'), ('Tour guide', 'Tour guide'), ('Midwife', 'Midwife'), ('Paramedic', 'Paramedic'), ('Machinist', 'Machinist'), ('Health professional', 'Health professional'), ('Optician', 'Optician'), ('Butcher', 'Butcher'), ('Tradesman', 'Tradesman'), ('Operator', 'Operator')], max_length=50)),
                ('State', models.CharField(choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='State', max_length=50)),
                ('Income', models.CharField(choices=[('None', 'None'), ('1k-9k', '1k-9k'), ('10k-30k', '10k-30k'), ('31k-40k', '31k-40k'), ('41k-50k', '41k-50k'), ('Above 50k', 'Above 50k')], default='Income', max_length=20)),
                ('Interest', multiselectfield.db.fields.MultiSelectField(choices=[('Gaming', 'Gaming'), ('Blogging', 'Blogging'), ('Sports', 'Sports'), ('Art & Design', 'Art & Design'), ('Traveling', 'Traveling'), ('Cooking', 'Cooking'), ('Music', 'Music'), ('Reading', 'Reading'), ('Collecting', 'Collecting'), ('Painting', 'Painting'), ('Dancing', 'Dancing'), ('Computer', 'Computer'), ('Animal Care', 'Animal Care'), ('Gardening', 'Gardening'), ('Yoga', 'Yoga'), ('Computer Programming', 'Computer Programming'), ('Mathematics', 'Mathematics'), ('Teaching', 'Teaching'), ('Adventure', 'Adventure'), ('Shopping', 'Shopping'), ('Photography', 'Photography'), ('Movie', 'Movie')], max_length=210)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
