# Generated by Django 3.0.7 on 2020-06-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetryAccount', '0003_auto_20200617_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateProfile',
        ),
    ]
